apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: app
spec:
  type: ExternalName
  externalName: dev-mysql.cmtgwe8q2w1g.us-east-1.rds.amazonaws.com
  ports:
    - port: 3306
      targetPort: 3306
