apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      containers:
        - name: app
          image: 175200623112.dkr.ecr.us-east-1.amazonaws.com/three-tier-app:33caebf
          ports:
            - containerPort: 4000
          env:
            - name: AWS_REGION
              value: "us-east-1"
            - name: DB_SECRET_NAME
              value: "dev/three-tier-app/db"
            - name: DB_USER
              value: "appuser"
            # DB_PASSWORD fetched from AWS Secrets Manager via IRSA (dev/three-tier-app/db)
            # Do NOT hardcode credentials here
            - name: DB_HOST
              value: "dev-mysql.cmtgwe8q2w1g.us-east-1.rds.amazonaws.com"
            - name: DB_NAME
              value: "appdb"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: app
spec:
  selector:
    app: app
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
